import { invoke } from "@tauri-apps/api/core";
import type { ApprovalDecision, ApprovalMode, ApprovalRequest, CodexChangeGroupV1, CodexChangeHistoryEntryV1, CodexCompatibilityReport, CodexConnectResult, CodexHistoryChangeInput, CodexHistoryPreview, DocumentData, EditorContextV1, PhitsAgentSetupStatus, PhitsAppSettings, RuntimeDiagnostics, StartupOpenRequest, UtilityKind, WorkspaceInfo } from "./types";

export const api = {
  openWorkspace: (path: string, restoreRunState = true, preferredInput?: string) => invoke<WorkspaceInfo>("workspace_open", { path, restoreRunState, preferredInput }),
  takeStartupOpenRequests: () => invoke<StartupOpenRequest[]>("startup_take_open_requests"),
  resolveStartupOpenTarget: (path: string) => invoke<StartupOpenRequest>("startup_resolve_open_target", { path }),
  readDocument: (workspaceRoot: string, relativePath: string) => invoke<DocumentData>("document_read", { workspaceRoot, relativePath }),
  saveDocument: (workspaceRoot: string, document: DocumentData, content: string) => invoke<DocumentData>("document_save", { workspaceRoot, document, content }),
  saveDocumentAs: (workspaceRoot: string, targetPath: string, content: string, sourceDocument?: DocumentData | null) => invoke<DocumentData>("document_save_as", { workspaceRoot, targetPath, content, sourceDocument: sourceDocument ?? null }),
  diagnostics: (workspaceRoot?: string) => invoke<RuntimeDiagnostics>("runtime_diagnose", { workspaceRoot }),
  codexCompatibilityProbe: (force = false) => invoke<CodexCompatibilityReport>("codex_compatibility_probe", { force }),
  getPhitsSettings: () => invoke<PhitsAppSettings>("phits_settings_get"),
  setPhitsSettings: (phitsRoot?: string | null) => invoke<PhitsAppSettings>("phits_settings_set", { phitsRoot: phitsRoot ?? null }),
  loadLanguageSpec: (phitsRoot?: string) => invoke<unknown>("language_spec_load", { phitsRoot }),
  runNormal: (workspaceRoot: string, inputRelativePath?: string, overrideUnresolved = false) => invoke("run_phits_normal", { workspaceRoot, inputRelativePath, overrideUnresolved }),
  runProduction: (workspaceRoot: string, inputRelativePath?: string, overrideUnresolved = false) => invoke("run_phits_production", { workspaceRoot, inputRelativePath, overrideUnresolved }),
  stopGracefully: (workspaceRoot: string, inputRelativePath?: string) => invoke("run_phits_stop_graceful", { workspaceRoot, inputRelativePath }),
  runUtility: (workspaceRoot: string, kind: UtilityKind, relativePath: string) => invoke("run_utility", { workspaceRoot, kind, relativePath }),
  inspectPhitsAgentSetup: (workspaceRoot: string) => invoke<PhitsAgentSetupStatus>("phits_agent_setup_inspect", { workspaceRoot }),
  codexConnect: (workspaceRoot: string) => invoke<CodexConnectResult>("codex_connect", { workspaceRoot }),
  codexDisconnect: () => invoke("codex_disconnect"),
  codexThreadStart: (workspaceRoot: string, model?: string, reasoningEffort?: string) => invoke<string>("codex_thread_start", { workspaceRoot, model, reasoningEffort }),
  codexThreadResume: (workspaceRoot: string, threadId: string) => invoke("codex_thread_resume", { workspaceRoot, threadId }),
  codexThreadRename: (workspaceRoot: string, threadId: string, title: string) => invoke("codex_thread_rename", { workspaceRoot, threadId, title }),
  codexThreadDelete: (workspaceRoot: string, threadId: string) => invoke("codex_thread_delete", { workspaceRoot, threadId }),
  codexTurnStart: (threadId: string, text: string, context: EditorContextV1 | null, approvalMode: ApprovalMode, model?: string, reasoningEffort?: string, forceReadOnly = false) => invoke("codex_turn_start", { threadId, text, context, approvalMode, model, reasoningEffort, forceReadOnly }),
  codexTurnInterrupt: (threadId: string, turnId: string) => invoke("codex_turn_interrupt", { threadId, turnId }),
  resolveApproval: (request: ApprovalRequest, decision: ApprovalDecision) => invoke("codex_approval_resolve", { requestId: request.requestId, method: request.method, decision }),
  beginCodexChangeHistory: (workspaceRoot: string, threadId: string | undefined, turnId: string | undefined, itemId: string | undefined, changes: CodexHistoryChangeInput[]) => invoke<string>("codex_change_history_begin", { workspaceRoot, threadId, turnId, itemId, changes }),
  completeCodexChangeHistory: (workspaceRoot: string, historyId: string) => invoke<CodexChangeHistoryEntryV1>("codex_change_history_complete", { workspaceRoot, historyId }),
  abortCodexChangeHistory: (workspaceRoot: string, historyId: string) => invoke("codex_change_history_abort", { workspaceRoot, historyId }),
  listCodexChangeHistory: (workspaceRoot: string) => invoke<CodexChangeHistoryEntryV1[]>("codex_change_history_list", { workspaceRoot }),
  listCodexChangeGroups: (workspaceRoot: string) => invoke<CodexChangeGroupV1[]>("codex_change_history_list_groups", { workspaceRoot }),
  previewCodexChangeHistory: (workspaceRoot: string, historyId: string) => invoke<CodexHistoryPreview>("codex_change_history_preview", { workspaceRoot, historyId }),
  previewCodexChangeGroup: (workspaceRoot: string, historyIds: string[]) => invoke<CodexHistoryPreview>("codex_change_history_preview_group", { workspaceRoot, historyIds }),
  markCodexChangeGroupReviewed: (workspaceRoot: string, historyIds: string[]) => invoke<CodexChangeHistoryEntryV1[]>("codex_change_history_mark_reviewed", { workspaceRoot, historyIds }),
  revertCodexChangeHistory: (workspaceRoot: string, historyId: string) => invoke<CodexChangeHistoryEntryV1>("codex_change_history_revert", { workspaceRoot, historyId }),
  revertCodexChangeGroup: (workspaceRoot: string, historyIds: string[]) => invoke<CodexChangeHistoryEntryV1[]>("codex_change_history_revert_group", { workspaceRoot, historyIds }),
};
